### ISSUE TITLE
pb with operator x bang by D

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#193]
Hi,

...................#1.is.bugging#
.................................
.D1..........D2.....D1...........
.*:02f36.....*H.....*H...........
.............xS.....xS...........
.................................
.................................
....................:04E36.......
.................................
.................................
.................................
.................................
.................................
..............:24E36.............
.............J...................
..............:23C36.............

i met a bug when putting D1 to bang the x operator. Strange no ?

**Comment by nlebellier** [comment]
j'en profite pour demander comment faire un simple copier depuis l'extérieur d'ORCA  et ensuite de coller dans Orca ? Ce serait pratique pour tester des morceaux de code qui posent pb.

**Comment by bbarham** [comment]
I believe this is a limitation of the cardinal operators.
Paste this:
```
.#EEEEEEE.
```
then start the clock and delete the #. 
You'll see the E's collide into each other and create a line of bangs.

In your example, the S coming out of the x operator is colliding with the S that's already there before it moves out of the way.

**Comment by neauoire** [comment]
> j'en profite pour demander comment faire un simple copier depuis l'extérieur d'ORCA et ensuite de coller dans Orca ? Ce serait pratique pour tester des morceaux de code qui posent pb. Sous Linux.

You can simply copy/paste from outside of orca into a patch. If that is not working for you, you might want to install `xclip` on linux. It's what I use with Elementary, and it's pretty reliable.

As for the "bug", it's normal that `D1` cannot generate a series of S. Since orca operates from the top/left to the bottom/down, you can't send a sequence of S down, E right, etc - Because the first E collides with the second one, and so on.

`X` locks the output, so it cannot do what you need, but the best way to achieve that would be to use `Y` or write directly. This is not really a bug, it's kind of by design, if I unlock the `X` and `O` outputs, that means that you won't be able to write a letter safely in some other cases.

**Comment by nlebellier** [comment]
Thanks for your explanations. I should have guess...
