### ISSUE TITLE
NPM, permissions on chrome-sandbox

### ISSUE THREAD

**Issue by VegaDeftwing** [hundredrabbits/Orca#91]
```
> Orca@0.1.0 start (The Place I Downloaded Orca to)/Orca/desktop
> electron .

[10871:0426/220305.133470:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary
 was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You
 need to make sure that
(The Place I Downloaded Orca to)/Orca/desktop/node_modules/electron/dist/chrome-sandbox
is owned by root and has mode 4755.
```
This is the result if I run from a manual git clone, even after changing the permissions and owner accordingly, The same issue comes up for the ITCH version, although changing the permission and owner as suggested does fix it in that case- I'd just rather not use the ITCH updater

**Comment by neauoire** [comment]
Cannot reproduce.

**Comment by VegaDeftwing** [comment]
Odd, I'll try it on a different system entirely tomorrow. For more information, on Arch Linux, Kernel 5.0.9 with everything up to date.

**Comment by neauoire** [comment]
Keep me posted :)

**Comment by ghostvar** [comment]
I have same issues, when using electron 5 on Arch Linux with kernel 5.0.9
and here is how to fix:
https://github.com/jiahaog/nativefier/issues/666

**Comment by neauoire** [comment]
Possibly related: 
https://github.com/electron/electron/issues/16631

**Comment by neauoire** [comment]
Try now, we've updated Electron to 5.0.1

**Comment by VegaDeftwing** [comment]
new update didn't fix it. Trying to do the fix @ghostvar linked to but I'm not sure what file to patch

**Comment by neauoire** [comment]
I understand, I just closed it because it's not a Orca related issue.
Either Electron fixes it, or the change have to be applied on the client's side.

**Comment by fasterthanlime** [comment]
Found this issue by accident (sorry for necroing, @neauoire!), but I just wanted to say that:

This is *not* the same issue as electron 2.x crashing with glibc 2.28.

This issue is because electron 5.x+ now enables Chromium's SUID sandbox by default, and:

  * It works fine on, say, Ubuntu, because its kernel "supports unprivileged CLONE_NEWUSER" by default (see https://github.com/electron/electron/issues/17972 )
  * It does /not/ work fine on Arch, because its default kernel doesn't.

A dirty workaround in the meantime is to run electron with `--no-sandbox`:

```
electron . --no-sandbox
```

Alternatively, you could export `ELECTRON_DISABLE_SANDBOX=1` before running `electron .`

(Of course, the best fix is to change the kernel you're using, but this is non-trivial..)
